### ISSUE TITLE
GitHub user registration

### ISSUE THREAD

**Issue by andreasindal** [nekosaur/mashup#1]
Implementation of user registration using OAuth2 with GitHub.

**Comment by nekosaur** [comment]
User registration through GitHub is currently working using passport on backend for both initial redirect and callback. We should try to redirect from frontend instead, and send code to backend (passport?) so that it can retrieve access token and then return JWT token to frontend (#16).

**Comment by nekosaur** [comment]
Latest pull request made github oauth authorization work without passport (satellizer + node-oauth instead). Code still needs to be cleaned up, preferably done with promises.

**Comment by nekosaur** [comment]
Code is now using promises
